# Preview Databases Ethereum Dataset

In [ ]:
# Execute Query to get sum and average transacction gas fees ETH per day
query_string = """
SELECT
  SUM(value/POWER(10,18)) AS sum_tx_ether,
  AVG(gas_price*(receipt_gas_used/POWER(10,18))) AS avg_tx_gas_cost,
  DATE(timestamp) AS tx_date
FROM
  `bigquery-public-data.crypto_ethereum.transactions` AS transactions,
  `bigquery-public-data.crypto_ethereum.blocks` AS blocks
WHERE TRUE
  AND transactions.block_number = blocks.number
  AND receipt_status = 1
  AND value > 0
GROUP BY tx_date
HAVING tx_date >= '2018-01-01' AND tx_date <= '2022-05-31'
ORDER BY tx_date
"""

dataframe = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        create_bqstorage_client=True,
    )
)
print(dataframe.head())

   sum_tx_ether  avg_tx_gas_cost     tx_date
0  8.246872e+06         0.000537  2018-01-01
1  1.398478e+07         0.000584  2018-01-02
2  1.397559e+07         0.000605  2018-01-03
3  2.023177e+07         0.000700  2018-01-04
4  1.851769e+07         0.001925  2018-01-05

In [ ]:
# Create plot with Average Ether transactions cost by day
plt.style.use('ggplot')
sns.set_context("notebook", font_scale=1.3, rc={"lines.linewidth": 0.5})

f, g = plt.subplots(figsize=(12, 9))
g = sns.lineplot(x="tx_date", y="avg_tx_gas_cost", data=dataframe, palette="Blues_d")
plt.title("Average Ether transaction cost over time")
plt.show(g)

In [ ]:
# Execute Query to get transacction ETH per day
query_string = """
SELECT *
FROM
    `bigquery-public-data.crypto_ethereum.transactions` AS transactions
    WHERE DATE(block_timestamp) = "2022-06-10"
    LIMIT 1000
"""

df_transacctions = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        create_bqstorage_client=True,
    )
)

In [ ]:
df_transacctions

,hash,nonce,transaction_index,from_address,to_address,value,gas,gas_price,input,receipt_cumulative_gas_used,...,receipt_contract_address,receipt_root,receipt_status,block_timestamp,block_number,block_hash,max_fee_per_gas,max_priority_fee_per_gas,transaction_type,receipt_effective_gas_price
0,0xe7e7d896087741ce7e67ef2bdb53e6c3da6a0616c02b...,2,10,0x9f4a0b3dd028aeb1aa5e5908fe951c5f22c0f0a5,0x06f6c1c9d26f9420d936807e13692c20cbb93370,10000000000000000.000000000,61614,119627146807,0xa71bbebe000000000000000000000000000000000000...,912331,...,None,None,1,2022-06-10 00:40:03+00:00,14935552,0x4f1f84370ede1e188834c21eadacbee83a8e6ceb762c...,200000000000,35000000000,2,119627146807
1,0x8fbc25c6e37624929bebd6ece1ceb64480c9b4810543...,157,41,0x70c70d56073c6d73441917a1bb715e560e5c8a89,0x430fef0e064dfde9f72888bd6f619fa58e7723e6,0E-9,130874,64951863181,0xa0712d68000000000000000000000000000000000000...,3024075,...,None,None,1,2022-06-10 04:47:57+00:00,14936576,0x81f1060cd1ed3c86eebda886d9f31bf11cc46755e5d9...,174320000000,4260000000,2,64951863181
2,0x467d42134c75eb0c75b982f3c2ab3f31f8a54e3a45d0...,537,43,0x99f7ed1a874f06cdd5ecde93e59b0ceb1af44d6b,0x430fef0e064dfde9f72888bd6f619fa58e7723e6,0E-9,130874,64951863181,0xa0712d68000000000000000000000000000000000000...,3242199,...,None,None,1,2022-06-10 04:47:57+00:00,14936576,0x81f1060cd1ed3c86eebda886d9f31bf11cc46755e5d9...,174320000000,4260000000,2,64951863181
3,0x32aa26b56ab4d344d03bdf67cb521e904389762b840f...,42488,0,0xe92f359e6f05564849afa933ce8f62b8007a1d5d,0x9008d19f58aabd9ed0d60971565aa8510560ab41,0E-9,340944,67087371480,0x13d79a0b000000000000000000000000000000000000...,273542,...,None,None,1,2022-06-10 04:47:57+00:00,14936576,0x81f1060cd1ed3c86eebda886d9f31bf11cc46755e5d9...,107910134806,6395508299,2,67087371480
4,0x8ef44547b80026c04e096f872d0d652b506220f2c75e...,16,7,0x368f88ab65860e8f69bb4753800d6b77ecd209d8,0x430fef0e064dfde9f72888bd6f619fa58e7723e6,0E-9,141780,80691863181,0xa0712d68000000000000000000000000000000000000...,1174001,...,None,None,1,2022-06-10 04:47:57+00:00,14936576,0x81f1060cd1ed3c86eebda886d9f31bf11cc46755e5d9...,200000000000,20000000000,2,80691863181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0xb961ef5e99413349edc13474387da29cb514be1c42fc...,90,72,0xa06625e46359b2beef408ad0e53073a73e54bbd2,0x45a5616c9d79951c08d53dd6b6b0ccdc93fc9389,0E-9,105975,62424776283,0xa0712d68000000000000000000000000000000000000...,6804350,...,None,None,1,2022-06-10 18:22:34+00:00,14939918,0xcca8927594b1dd5be49862b88dcc57047e972f4162a8...,100000000000,6000000000,2,62424776283
996,0x5207f34c417aa5f0bc07a04dab04ad5214c20feabc8e...,17,195,0xe4b143f745e15c4e13ff000b9cbfe31e77adf4eb,0x45a5616c9d79951c08d53dd6b6b0ccdc93fc9389,0E-9,105975,58604776283,0xa0712d68000000000000000000000000000000000000...,16757467,...,None,None,1,2022-06-10 18:22:34+00:00,14939918,0xcca8927594b1dd5be49862b88dcc57047e972f4162a8...,82310000000,2180000000,2,58604776283
997,0x9542c4030bdf08228922c70ba44310b058730ff3bec3...,660,112,0x2e89cf7bf300385e4a5a5b3c727f36aac15667f2,0x45a5616c9d79951c08d53dd6b6b0ccdc93fc9389,0E-9,105975,62424776283,0xa0712d68000000000000000000000000000000000000...,10336870,...,None,None,1,2022-06-10 18:22:34+00:00,14939918,0xcca8927594b1dd5be49862b88dcc57047e972f4162a8...,140000000000,6000000000,2,62424776283
998,0x6e7338218ce21c492b32a9e9ba10c3639aa26d2e1b86...,47401,57,0xa5a13f62ce1113838e0d9b4559b8caf5f76463c0,0x4cb18386e5d1f34dc6eea834bf3534a970a3f8e7,17159.000000000,900000,63829593781,0x1cff79cd000000000000000000000000343933efdf64...,5546968,...,None,None,0,2022-06-10 18:22:34+00:00,14939918,0xcca8927594b1dd5be49862b88dcc57047e972f4162a8...,135730796433,7404817498,2,63829593781
999,0x8b73c68b232e2af14e1403703329d66941c7c5541615...,183632,108,0xa108a7c2559ceedb547fd65c07922143bfc3318c,0x9487a68681f8e114787c97079ed3e8135e12bca6,37883170000000000.000000000,21000,56809884165,0x,8262769,...,None,None,1,2022-06-10 19:30:07+00:00,14940174,0xffbfbdf1f22a820f259252923a2182586da929d32e8d...,75206683560,4187000000,2,56809884165

In [ ]:
# Execute Query to get transacction ETH per day
query_string = """
SELECT *
FROM
    `bigquery-public-data.crypto_ethereum.traces` AS traces
    WHERE DATE(block_timestamp) = "2022-06-10"
    LIMIT 1000
"""

df_traces = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        create_bqstorage_client=True,
    )
)

In [ ]:
df_traces

,transaction_hash,transaction_index,from_address,to_address,value,input,output,trace_type,call_type,reward_type,gas,gas_used,subtraces,trace_address,error,status,block_timestamp,block_number,block_hash,trace_id
0,0x7d0fbab3b7f3d780c6cc4db083a1018172578b09bd2c...,253,0x8e9b1683a83f1485422e30e37dac1977c79f3e44,0xbaf2127b49fc93cbca6269fade0f7f31df4c88a7,0E-9,0xfb16a5950000000000000000000000009a930486b8f6...,None,call,delegatecall,None,179452.0,NaN,1,"0,5,0,1",Reverted,0,2022-06-10 14:40:03+00:00,14938971,0x5059c995a9ad1bb44be9abae0edf3e59de83e12665c6...,call_0x7d0fbab3b7f3d780c6cc4db083a1018172578b0...
1,0x1934908e4e56c6f87228f57f6ce688231dab9fc8fc7c...,229,0x74312363e45dcaba76c59ec49a7aa8a65a67eed3,0x6d7812d41a08bc2a910b562d8b56411964a4ed88,70000000000000000.000000000,0x357a150b000000000000000000000000000000000000...,None,call,delegatecall,None,390198.0,NaN,2,"1,0,0",Reverted,0,2022-06-10 09:24:01+00:00,14937658,0x4fbb42384f59d6395a8eece82e465f397ce55c5df4c7...,call_0x1934908e4e56c6f87228f57f6ce688231dab9fc...
2,0xa63e34e7d869bac3068fbe90deded1c36fd33fd2cfab...,34,0x60594a405d53811d3bc4766596efd80fd545a270,0xa56006a9bc78fd64404b34d44f06d1141f8589be,0E-9,0xfa461e33000000000000000000000000000000000000...,None,call,call,None,739141.0,NaN,0,"0,1,0,2",Reverted,0,2022-06-10 14:52:05+00:00,14939028,0x9e3d6af92a3bf3b187199452fe268e4f5daeef303f89...,call_0xa63e34e7d869bac3068fbe90deded1c36fd33fd...
3,0xcdfe0c04f1c6a58be397fbb35db36132adc9043637f3...,238,0x09d402eadc7a78dadfc618ae623af7bc8a67656f,0x6fb42a71b305dafb98688ba9fa76791342ad52a3,0E-9,0x23b872dd000000000000000000000000bf76e026ef36...,None,call,call,None,59658.0,NaN,0,"2,5,0,1,0",Reverted,0,2022-06-10 13:23:59+00:00,14938650,0x18ff458891e08ae7003a40673a394d9c33ef05f79967...,call_0xcdfe0c04f1c6a58be397fbb35db36132adc9043...
4,0xd6a9991623906341cacc6ce5e42d680a79d70c3d5eba...,128,0x45d5daecb6e96c87fa04105ee205379ddfe8f555,0x4205e2676c03cf0d68a24286c23d43f276369e57,0E-9,0xa24258ad000000000000000000000000000000000000...,None,call,staticcall,None,2773503.0,NaN,13,"0,0,1,1,7,1,2",Reverted,0,2022-06-10 12:50:32+00:00,14938498,0x8b5268f6d23122fea8ea5e5526bbb67c980b0b76c471...,call_0xd6a9991623906341cacc6ce5e42d680a79d70c3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0xa2fad0110574e4ceb0ccae08ec16cbf305093ff723f9...,152,0x7f268357a8c2552623316e2562d90e642bb538e5,0x5b3256965e7c3cf26e11fcaf296dfc8807c01073,6600000000000000.000000000,0x,0x,call,call,None,2300.0,0.0,0,"2,1",None,1,2022-06-10 08:43:04+00:00,14937492,0xad70d4a7f06440f114bb2b0f56260a6cca6721d8fce3...,call_0xa2fad0110574e4ceb0ccae08ec16cbf305093ff...
996,0x54a5ce1510737fe0fd6378a7f7631b327f1f0783597d...,390,0x130c8052e6fc6027c5d0b2f70b81cffd57368275,0x02d24cab4f2c3bf6e6eb07ea07e45f96baccffe7,230000000000000.000000000,0x,0x,call,call,None,2300.0,0.0,0,"4,0,0,1",None,1,2022-06-10 16:44:11+00:00,14939522,0x4b4f1a81158ede847baf5e411aef1f93fa8ae0166144...,call_0x54a5ce1510737fe0fd6378a7f7631b327f1f078...
997,0xd404cb67b2bb795206e58097aeddbd0ee0a0f2007993...,280,0x7f268357a8c2552623316e2562d90e642bb538e5,0x5b3256965e7c3cf26e11fcaf296dfc8807c01073,750000000000000.000000000,0x,0x,call,call,None,2300.0,0.0,0,"4,1",None,1,2022-06-10 00:43:00+00:00,14935560,0x881dd288cae0a2c905bf563ba7b78ec400e5b6e05616...,call_0xd404cb67b2bb795206e58097aeddbd0ee0a0f20...
998,0xddcafbe488a947068ad3f6964d3b4d6b2c88e0d7e056...,11,0x283af0b28c62c092c9727f1ee09c02ca627eb7f5,0x099df93477a50bdc14b95a2ef3c5f8242c40ed8f,950852611389659.000000000,0x,0x,call,call,None,2300.0,0.0,0,10,None,1,2022-06-10 18:29:54+00:00,14939952,0x58299793da394adc437eb9d10fb75bfbbf0851f36f56...,call_0xddcafbe488a947068ad3f6964d3b4d6b2c88e0d...
999,0xb97edf737816e59e27e589dec03a5f760137765b296c...,37,0xd152f549545093347a162dce210e7293f1452150,0x46dc6cacb2cdf6a76236f834a7b61ea19493c1e9,75000000000000000.000000000,0x,0x,call,call,None,2300.0,0.0,0,9,None,1,2022-06-10 07:49:43+00:00,14937291,0x32e8b25ec0800d2a6841898d6e88dc809978368f8aee...,call_0xb97edf737816e59e27e589dec03a5f760137765...

In [ ]:
# Execute Query to get transacction ETH per day
query_string = """
SELECT *
FROM
    `bigquery-public-data.crypto_ethereum.tokens`
    WHERE DATE(block_timestamp) = "2022-06-10"
    LIMIT 1000
"""

df_tokens = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        create_bqstorage_client=True,
    )
)

In [ ]:
df_tokens

In [ ]:
# Execute Query to get transacction ETH per day
query_string = """
SELECT *
FROM
    `bigquery-public-data.crypto_ethereum.token_transfers`
    WHERE DATE(block_timestamp) = "2022-06-10"
    LIMIT 1000
"""

df_token_transfers = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        create_bqstorage_client=True,
    )
)

df_token_transfers

,token_address,from_address,to_address,value,transaction_hash,log_index,block_timestamp,block_number,block_hash
0,0xc00e94cb662c3520282e6f5717214004a7f26888,0xf1b5ca4134caf84640d0c0f9113b4b67c445e35e,0xfb2a52012f5e757ba748d1f8d7f582b8d1a613c0,31128885436896595,0xe53c39cec74995af2da2f2aeb902be28129a543a7b26...,335,2022-06-10 11:50:24+00:00,14938261,0xb65e99f95f5057e1af31d64011b164fe4172da5a3c47...
1,0xdac17f958d2ee523a2206206994597c13d831ec7,0x29d5527caa78f1946a409fa6acaf14a0a4a0274b,0x20e315ceaa2b3730e1267c0ee615afbfe79ec25e,205690000,0xc6a5235cae16e83aae526b874a4a848f7efd7fe36bd9...,196,2022-06-10 11:50:24+00:00,14938261,0xb65e99f95f5057e1af31d64011b164fe4172da5a3c47...
2,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc58bb74606b73c5043b75d7aa25ebe1d5d4e7c72,0x59ee1da6ddd19ae0f87195b5343e51c1ae69a53a,99952218,0x6f3348c1023e45c86b5b2c4e8d3d2957d96abf1275da...,107,2022-06-10 11:50:24+00:00,14938261,0xb65e99f95f5057e1af31d64011b164fe4172da5a3c47...
3,0xaeb813653bb20d5fa4798dc4fc63af9cad4f3f67,0x3acce2a7609d6714cfb1394ccf37069a02843029,0x6ff1c63921441114402c8bbb4c86ca8d4222911f,255000000000000000000000,0x49715bb6165fccd47832b8c4c3b0669945c1dc7656ef...,258,2022-06-10 11:50:24+00:00,14938261,0xb65e99f95f5057e1af31d64011b164fe4172da5a3c47...
4,0xed04915c23f00a313a544955524eb7dbd823143d,0x0084dfd7202e5f5c0c8be83503a492837ca3e95e,0x6d97b2607878f55fc72485be5b73bb6dbbeb808b,361714589743286,0xbf6ac237751da07b429d27e8f241a97f9eeceedec2cf...,31,2022-06-10 11:50:24+00:00,14938261,0xb65e99f95f5057e1af31d64011b164fe4172da5a3c47...
...,...,...,...,...,...,...,...,...,...
995,0xdac17f958d2ee523a2206206994597c13d831ec7,0x8191e8a6f936c547b9abfd626fd98de07bceed18,0xec30d02f10353f8efc9601371f56e808751f396f,175232572,0x0230f12e9aebd58ed06593e12d2173140e9a9ec0b747...,262,2022-06-10 15:19:00+00:00,14939145,0x75ca1d99c0cb46d36e430c8c1a3ebf50e73f5900e771...
996,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xba12222222228d8ba445958a75a0704d566bf2c8,0x56178a0d5f301baf6cf3e1cd53d9863437345bf9,1769531249839190346,0xdbb33dfe1a3a4301bfaa81811b2cbc94af39af72f98b...,118,2022-06-10 15:19:00+00:00,14939145,0x75ca1d99c0cb46d36e430c8c1a3ebf50e73f5900e771...
997,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xdf50fbde8180c8785842c8e316ebe06f542d3443,0x0000000000007f150bd6f54c40a34d7c3d5e9f56,24089435974,0x6b3b46e207ea75a138d50ce3932f64cedd86b96ffca5...,4,2022-06-10 15:19:00+00:00,14939145,0x75ca1d99c0cb46d36e430c8c1a3ebf50e73f5900e771...
998,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x0ab62ef56cc40ee4014e9376d5841877a7cc999f,0x53c218ee4b05f817fab41afd2c66fd92550a8888,280100000000000000,0x8c752f4efa3a00d9e02a883159330c3bcc0ec0b2bfb2...,124,2022-06-10 15:19:00+00:00,14939145,0x75ca1d99c0cb46d36e430c8c1a3ebf50e73f5900e771...
999,0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0,0xddfabcdc4d8ffc6d5beaf154f18b778f892a0740,0xadc3c1e03fee262c378b174646410d787700bdf3,30918668200000000000,0x554d0f96bad1d1a4a881fdd648035833295aec64da51...,233,2022-06-10 15:19:00+00:00,14939145,0x75ca1d99c0cb46d36e430c8c1a3ebf50e73f5900e771...

In [ ]:
# Execute Query to get transacction ETH per day
query_string = """
SELECT *
FROM
    `bigquery-public-data.crypto_ethereum.sessions`
    LIMIT 1000
"""

df_sessions = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        create_bqstorage_client=True,
    )
)

df_sessions

,id,start_trace_id,start_block_number,start_block_timestamp,wallet_address,contract_address
0,2309e81974f2bd037a9e67e439a48893,call_0x1a5b4e904670b4c224c9482559f5e946ffceafd...,475577,2015-11-01 22:53:50+00:00,0x0008973f5772ff0d13cdb64fa10fc35cbf71d03c,0x0098488dd3fadc51313f40d7248c4107a96691ef
1,c12f28333c0df4c95df7e8d633d9aa1a,call_0x0387a8c3308967571c7254764cf0e7af23c9a21...,576581,2015-11-21 22:30:13+00:00,0x001356974cded070ea3beb7dcf61f6878bea6c22,0x70b2f497d45795e9b02f75e6d7fa4d3f1345ffd2
2,2a0ded878c9f5471f37794b1ee7c5e03,call_0xb1999e26e5f7afe55c75401b15f4201a7d5485e...,662285,2015-12-09 00:48:00+00:00,0x001356974cded070ea3beb7dcf61f6878bea6c22,0x70b2f497d45795e9b02f75e6d7fa4d3f1345ffd2
3,95b4adb835cd55cd19ae0a428f64e60e,call_0xc44b9de5ead33b1e72e45dfb7683554e2b58300...,439800,2015-10-25 22:39:52+00:00,0x001356974cded070ea3beb7dcf61f6878bea6c22,0x70b2f497d45795e9b02f75e6d7fa4d3f1345ffd2
4,2144ce02f3f7d98c5f365bcd62940f07,call_0x4fca832d2df7b2b1606d2bc18d04ced10c85c36...,499516,2015-11-06 15:42:44+00:00,0x001356974cded070ea3beb7dcf61f6878bea6c22,0x70b2f497d45795e9b02f75e6d7fa4d3f1345ffd2
...,...,...,...,...,...,...
995,beb33cfe822b3222f1bec34ba7115ea8,call_0x68302d4725b0fe2f93408a53b54433f0ca7b657...,627709,2015-12-02 02:00:42+00:00,0x0142b986f0761e770a94198e8fba8e5d1d84483f,0x576f13dded1f2ad6b9d55ee8a1b67815ee7c92d9
996,0bd50fb4dc0bc35cdc1d6109b0a0e363,call_0x0ea7f09eec4d1f03aa5b6204c46d8fab5edbc04...,637656,2015-12-04 01:35:54+00:00,0x0151400dc9e881a37223afb2011495765f4f7247,0x74f2f93d5f837dfdcdb641c89dcd50f7a02fdf5d
997,cdacd13f96f7efdcbb17f3297d9acaa6,call_0xf08eaf974f3f85c76b98ddd3601c981402ca5b7...,638173,2015-12-04 03:59:59+00:00,0x0151400dc9e881a37223afb2011495765f4f7247,0x81f052a1735865118214f45f85f963a028c584c7
998,d5d93fe9270e6436a42c304b19fd5d61,call_0x28dfdf333062f347a2902d7072f5d387beadcf7...,637752,2015-12-04 02:03:59+00:00,0x0151400dc9e881a37223afb2011495765f4f7247,0x8bc8938363945be2319cdd418b40ed90915a65b2
999,e094ca0ce545b01dd3a487f2b8dfa5d9,call_0xdd572a84c6b7977040b5913f92d46cf345d3d08...,638102,2015-12-04 03:40:17+00:00,0x0151400dc9e881a37223afb2011495765f4f7247,0x8bc8938363945be2319cdd418b40ed90915a65b2

In [ ]:
# Execute Query to get transacction ETH per day
query_string = """
SELECT *
FROM
    `bigquery-public-data.crypto_ethereum.amended_tokens`
    LIMIT 1000
"""

df_amended_tokens = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        create_bqstorage_client=True,
    )
)

df_amended_tokens

,address,symbol,name,decimals
0,0x1b54a1f319cab3b09d0dda10c7ee55485d96eb87,RDCN,RDCOIN,18
1,0xecba3472395b7b8da221b56ef4a2fa8aeb684cf1,SHA,Achille Jamier Token,4
2,0x7d7c6e16a0b1c289c6211230cb85cdbfe213617c,TAO,Tao,18
3,0x3c4db6e4df1cebaa4d8fd025e91e43ac87480ed2,GINU,Giza Inu,9
4,0x730046165e8458549e8713d24f94cb5363406c98,TKN,ERC20 Tokenized Native Token,18
...,...,...,...,...
995,0xfdf40fc93023b8c5e397ca3bbd9c661819c2eb81,None,None,18
996,0x47010bfcdebde5c6f0cb3426cee269a96f7ac6ce,BTNT,BitNautic Token,18
997,0x0bddc07bfd25173e021bb8798aec238c699a0bac,None,None,18
998,0x35e5d95600ce1b7a5eae7cb924b2ee0bf44f254a,PAY,TenX Pay Token,18
999,0x4cf4015f096d2987391bcb55ecad4128c5cc9b19,PLPD,Polypanda,18

In [ ]:
# Execute Query to get transacction ETH per day
query_string = """
SELECT *
FROM
    `bigquery-public-data.crypto_ethereum.balances`
    LIMIT 1000
"""

df_balances = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        create_bqstorage_client=True,
    )
)

df_balances

                                        address                  eth_balance
0    0xce4041b5cffa8d9402b3ac441102c26e4757a377               9984.000000000
1    0x6a2a5bfcd12f7cc759f777512ab7516071fd553e                         0E-9
2    0xfdb6bb50564a64bc8ef62516c04b4d20e5275d39   1169653545375000.000000000
3    0x08e8f148a43fe84d206f2b79a1be6e520df44b35                  1.000000000
4    0xbdc89e7676bdba86eff0875f99f40a1a42ff7982   2348134412400000.000000000
..                                          ...                          ...
995  0x03cdab2770bdfa9024dabe43707d25b2692a6848               5000.000000000
996  0x196186a71ee051ae44f34b626926216a8a145b35   5929605000000000.000000000
997  0x32b14a63f53645d9801bf92f20f5c0a39072eed7                         0E-9
998  0xd134e1bb9c963ba0efbca73dc86a72a85f2b176e                         0E-9
999  0x59e84f54e37e23411c4a7157a4a8990950345169  96701815000000000.000000000

[1000 rows x 2 columns]

In [ ]:
# Execute Query to get transacction ETH per day
query_string = """
SELECT *
FROM
    `bigquery-public-data.crypto_ethereum.logs`
    LIMIT 1000
"""

df_logs = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        create_bqstorage_client=True,
    )
)

df_logs

,log_index,transaction_hash,transaction_index,address,data,topics,block_timestamp,block_number,block_hash
0,69,0x4d5a3e5fe46d068b2184ed6f6af11380efa83a0e0796...,12,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x00000000000000000000000000000000000000000000...,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,2022-06-13 12:18:51+00:00,14955951,0x07ab2c783a4d6590a18f1abcaa9d4fd5c8595dbdc413...
1,31,0xd1e4b0dc56b50a1acd4f6937d1d446f1b9d00743358b...,7,0xba12222222228d8ba445958a75a0704d566bf2c8,0x00000000000000000000000000000000000000000000...,[0x2170c741c41531aec20e7c107c24eecfdd15e69c9bb...,2022-06-13 12:18:51+00:00,14955951,0x07ab2c783a4d6590a18f1abcaa9d4fd5c8595dbdc413...
2,47,0xb84b8270d63874c5abd92865ac19dcc811288a72fab9...,9,0xc2adda861f89bbb333c90c492cb837741916a225,0x00000000000000000000000000000000000000000000...,[0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78...,2022-06-13 12:18:51+00:00,14955951,0x07ab2c783a4d6590a18f1abcaa9d4fd5c8595dbdc413...
3,86,0x51bc729af276f1554694f52f60d000a4e4c0b1091d77...,15,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x00000000000000000000000000000000000000000000...,[0x7fcf532c15f0a6db0bd6d0e038bea71d30d808c7d98...,2022-06-13 12:18:51+00:00,14955951,0x07ab2c783a4d6590a18f1abcaa9d4fd5c8595dbdc413...
4,3,0xf1ab5ce71bf267a2fb5d3266afd7044f28497f136382...,1,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x00000000000000000000000000000000000000000000...,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,2022-06-13 12:18:51+00:00,14955951,0x07ab2c783a4d6590a18f1abcaa9d4fd5c8595dbdc413...
...,...,...,...,...,...,...,...,...,...
995,271,0x84a45fbcd9d6c16688b66bedd4745777f0ece91c18dd...,209,0x56f98706c14df5c290b02cec491bb4c20834bb51,0x00000000000000000000000000000000000000000000...,[0xf6a97944f31ea060dfde0566e4167c1a1082551e64b...,2022-06-13 12:18:13+00:00,14955948,0xbe60537a6283553256e93560a04cd77bd01f6099e0ef...
996,521,0xe1d548f246cbac02a95488d0946b9b41988409db7d3a...,350,0x82c7a8f707110f5fbb16184a5933e9f78a34c6ab,0x,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,2022-06-13 12:18:13+00:00,14955948,0xbe60537a6283553256e93560a04cd77bd01f6099e0ef...
997,530,0x05dd810aa8e12f40975a96eb7f699f1780be98d1b7a6...,355,0x1ffe8a8177d3c261600a8bd8080d424d64b7fbc2,0x00000000000000000000000000000000000000000000...,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,2022-06-13 12:18:13+00:00,14955948,0xbe60537a6283553256e93560a04cd77bd01f6099e0ef...
998,193,0xcf11e30a2d38a5598fcd2d3cdd5b82a1ef7f48c48c54...,153,0x6b175474e89094c44da98b954eedeac495271d0f,0x00000000000000000000000000000000000000000000...,[0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b...,2022-06-13 12:18:13+00:00,14955948,0xbe60537a6283553256e93560a04cd77bd01f6099e0ef...
999,265,0xb8dc89a60461ef4806181a0160f9da59c5fec45208b2...,202,0xdac17f958d2ee523a2206206994597c13d831ec7,0x00000000000000000000000000000000000000000000...,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,2022-06-13 12:18:13+00:00,14955948,0xbe60537a6283553256e93560a04cd77bd01f6099e0ef...